// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkrwfrtjyvtqwvhnfahm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrcndmcnRqeXZ0cXd2aG5mYWhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjY3ODUsImV4cCI6MjA2NTYwMjc4NX0.kNp18SnYsdJ1B9KUQHg5Y_CIoNTrQ_gHX2C7L2Cs-Kg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);